version: "2"         # required to adjust maintainability checks
checks:
  similar-code:
    config:
      threshold: 120
  identical-code:
    config:
      threshold: 120
  method-complexity:
    config:
      threshold: 10
exclude_patterns:
 - "config/"
 - "db/"
 - "dist/"
 - "features/"
 - "**/node_modules/"
 - "script/"
 - "**/spec/"
 - "**/test/"
 - "**/tests/"
 - "Tests/"
 - "**/vendor/"
 - "**/*_test.go"
 - "**/*.d.ts"
